// File generated by FlutterFire CLI.
// This is a placeholder file. You need to run `flutterfire configure` to generate the actual configuration.
// For now, this file exists to prevent import errors.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_nyQAQYSo2b3i_o5A92_lGb6hsQnbBIA',
    appId: '1:776483653268:web:4b9b7d4d8b1f3e38bd5681',
    messagingSenderId: '776483653268',
    projectId: 'motivator-web',
    authDomain: 'motivator-web.firebaseapp.com',
    storageBucket: 'motivator-web.firebasestorage.app',
    measurementId: 'G-D3CPKQ5MWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcEsfNm1WRHg4L3nGAVR1Q9gQEzEZhuPE',
    appId: '1:776483653268:android:e6c941e8791a5964bd5681',
    messagingSenderId: '776483653268',
    projectId: 'motivator-web',
    storageBucket: 'motivator-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBixplaavv89TEgvOLRuLo2_9n5EMU-zYU',
    appId: '1:776483653268:ios:7949054a491a6a50bd5681',
    messagingSenderId: '776483653268',
    projectId: 'motivator-web',
    storageBucket: 'motivator-web.firebasestorage.app',
    iosBundleId: 'sh.digitalnomad.motivator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBixplaavv89TEgvOLRuLo2_9n5EMU-zYU',
    appId: '1:776483653268:ios:7949054a491a6a50bd5681',
    messagingSenderId: '776483653268',
    projectId: 'motivator-web',
    storageBucket: 'motivator-web.firebasestorage.app',
    iosBundleId: 'sh.digitalnomad.motivator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_nyQAQYSo2b3i_o5A92_lGb6hsQnbBIA',
    appId: '1:776483653268:web:673881d5da1bd457bd5681',
    messagingSenderId: '776483653268',
    projectId: 'motivator-web',
    authDomain: 'motivator-web.firebaseapp.com',
    storageBucket: 'motivator-web.firebasestorage.app',
    measurementId: 'G-YDBQJQ1WKP',
  );

}